### ISSUE TITLE
I want this

### ISSUE THREAD

**Issue by CitizenP5** [d3ward/toolz#106]
Hello,
I would like to load this as an HTML/CSS package on a web space and use it for my community as an AD check. I leave everything where it is. Your name and I will even make a donation to them. I just want to have this tool. I'm not familiar with "EJS". That's why I can't just take it over.

Hope to report.
LG CP

**Comment by d3ward** [comment]
Hi, you can fork, make sure you have npm and all the dependencies installed. Then build the files and you'll have the html+css+js only in a dist folder that can be hosted as static.
