### ISSUE TITLE
is 200 response with type ‘basic’ considered blocked a typo?

### ISSUE THREAD

**Issue by n690rp** [d3ward/toolz#108]
Our ad blocker sends a 204 No Content response and ads are blocked, but tools shows it as not blocked.

In fact, to show up as blocked the code appears to say type == ‘basic’ and statusCode == 200, then it is blocked, while everything else shows unblocked. Is that intentional or a typo? The logic appears reversed. To get a good score on tools, we have to send a malformed response, so that the catch phrase credits it as a blocked.

We would love to work with you more on this site, if you are still interested in maintaining it.

Thanks,
Andrew

**Comment by n690rp** [comment]
This is the part, I can’t quite get my mind around, 200 status, basic type shows blocked, otherwise not blocked:

adblock.js:390

                    "basic" == e.type && 200 == e.status ? (l.innerHTML = o.v + "<span>" + t + "</span>", _.blocked += 1, Object.assign(_.hosts[n][a], {
                        [t]: !0
                    }), y += "<br> " + t + " - blocked") : (s.style.background = "var(--red)", l.innerHTML = o.x + "<span>" + t + "</span>", _.notblocked += 1, Object.assign(_.hosts[n][a], {
                        [t]: !1
                    }), y += "<br> " + t + " - not blocked")

**Comment by d3ward** [comment]
Hi , 
It's not a typo, it's intentional and has logic behind it to solve the problem with CORS.
May I ask what adblock solution we are talking about here? In the project I implemented a compatibility table for this reason
