### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by netorola110** [d3ward/toolz#109]
### Context
**Browser**:
**OS**:
**Adblock Solution**(if any):

**Description of Issue**:

**Screenshots:**

[Attach screenshots here if applicable]

### Logs

**Test Result:**
[Describe the result of the test]

**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs or error messages from the developer console]

### Confirmation
- [x] I confirm that I have filled out all the necessary fields with enough detail to allow for the proper investigation and potential resolution of the issue.

**Comment by d3ward** [comment]
no info ..
