### ISSUE TITLE
Test failed, but NextDNS logs show blocked.

### ISSUE THREAD

**Issue by Alex67693** [d3ward/toolz#115]
### Context
**Browser**: Chrome 122.0.6261.90 
**OS**: Android 14
**Adblock Solution**(if any): NextDNS with Hagezi Ultimate

**Description of Issue**:

The adblocking Test shows 1% is blocked, but the NextDNS logs showing that every request from this test was blocked.

**Screenshots:**

[
![Screenshot_20240305_150540_Chrome](https://github.com/d3ward/toolz/assets/126346099/9a94a4f3-2792-4ef0-8693-093ef3f5767c)
![Screenshot_20240305_150429_Chrome](https://github.com/d3ward/toolz/assets/126346099/cfedbd1a-7126-423d-b5d7-1a31f3b494ec)]

### Logs

**Test Result:**
[1%]

**Test Log:**
[script_ads : false
script_pagead : false

-------------------------
Amazon => n° tests => 5
Google Ads => n° tests => 4
Doubleclick.net => n° tests => 5
Adcolony => n° tests => 4
Media.net => n° tests => 3
Ads => Total n° tests => 21
-------------------------
Google Analytics => n° tests => 4
Hotjar => n° tests => 7
MouseFlow => n° tests => 7
FreshWorks => n° tests => 3
Luckyorange => n° tests => 8
Stats WP Plugin => n° tests => 1
Analytics => Total n° tests => 30
-------------------------
Bugsnag => n° tests => 4
Sentry => n° tests => 2
Error Trackers => Total n° tests => 6
-------------------------
Facebook => n° tests => 2
Twitter => n° tests => 2
LinkedIn => n° tests => 2
Pinterest => n° tests => 5
Reddit => n° tests => 2
YouTube => n° tests => 1
TikTok => n° tests => 7
Social Trackers => Total n° tests => 21
-------------------------
Yahoo => n° tests => 11
Yandex => n° tests => 7
Unity => n° tests => 4
Mix => Total n° tests => 22
-------------------------
Realme => n° tests => 4
Xiaomi => n° tests => 7
Oppo => n° tests => 4
Huawei => n° tests => 6
OnePlus => n° tests => 2
Samsung => n° tests => 5
Apple => n° tests => 8
OEMs => Total n° tests => 36
-------------------------
cosmetic_static_ad : false

-------------------------
cosmetic_dynamic_ad : false

-------------------------

adtago.s3.amazonaws.com - not blocked
analyticsengine.s3.amazonaws.com - not blocked
analytics.s3.amazonaws.com - not blocked
advice-ads.s3.amazonaws.com - not blocked
advertising-api-eu.amazon.com - not blocked
pagead2.googlesyndication.com - not blocked
adservice.google.com - not blocked
pagead2.googleadservices.com - not blocked
afs.googlesyndication.com - not blocked
stats.g.doubleclick.net - not blocked
ad.doubleclick.net - not blocked
static.doubleclick.net - not blocked
m.doubleclick.net - not blocked
mediavisor.doubleclick.net - not blocked
ads30.adcolony.com - not blocked
adc3-launch.adcolony.com - not blocked
events3alt.adcolony.com - not blocked
wd.adcolony.com - not blocked
static.media.net - not blocked
media.net - not blocked
adservetx.media.net - not blocked
analytics.google.com - not blocked
click.googleanalytics.com - not blocked
google-analytics.com - not blocked
ssl.google-analytics.com - not blocked
adm.hotjar.com - not blocked
identify.hotjar.com - not blocked
insights.hotjar.com - not blocked
script.hotjar.com - not blocked
careers.hotjar.com - not blocked
surveys.hotjar.com - not blocked
events.hotjar.io - not blocked
mouseflow.com - not blocked
cdn.mouseflow.com - not blocked
o2.mouseflow.com - not blocked
gtm.mouseflow.com - not blocked
api.mouseflow.com - not blocked
cdn-test.mouseflow.com - not blocked
tools.mouseflow.com - not blocked
freshmarketer.com - not blocked
claritybt.freshmarketer.com - not blocked
fwtracks.freshmarketer.com - not blocked
luckyorange.com - not blocked
api.luckyorange.com - not blocked
w1.luckyorange.com - not blocked
realtime.luckyorange.com - not blocked
cdn.luckyorange.com - not blocked
analytics.query.yahoo.com - blocked
upload.luckyorange.net - not blocked
cs.luckyorange.net - not blocked
settings.luckyorange.net - not blocked
stats.wp.com - not blocked
notify.bugsnag.com - not blocked
browser.sentry-cdn.com - not blocked
app.bugsnag.com - not blocked
api.bugsnag.com - not blocked
sessions.bugsnag.com - not blocked
pixel.facebook.com - not blocked
app.getsentry.com - not blocked
analytics.pointdrive.linkedin.com - not blocked
ads-api.twitter.com - not blocked
ads.pinterest.com - not blocked
static.ads-twitter.com - not blocked
an.facebook.com - not blocked
ads.linkedin.com - not blocked
analytics.pinterest.com - not blocked
widgets.pinterest.com - not blocked
log.pinterest.com - not blocked
ads-api.tiktok.com - not blocked
trk.pinterest.com - not blocked
events.reddit.com - not blocked
analytics.tiktok.com - not blocked
ads.youtube.com - not blocked
events.redditmedia.com - not blocked
analytics-sg.tiktok.com - not blocked
ads-sg.tiktok.com - not blocked
business-api.tiktok.com - not blocked
ads.tiktok.com - not blocked
log.byteoversea.com - not blocked
ads.yahoo.com - not blocked
analytics.yahoo.com - not blocked
geo.yahoo.com - not blocked
udcm.yahoo.com - not blocked
log.fc.yahoo.com - not blocked
gemini.yahoo.com - not blocked
partnerads.ysm.yahoo.com - not blocked
advertising.yahoo.com - not blocked
udc.yahoo.com - not blocked
offerwall.yandex.net - not blocked
extmaps-api.yandex.net - not blocked
adtech.yahooinc.com - not blocked
appmetrica.yandex.ru - not blocked
advertising.yandex.ru - not blocked
adfox.yandex.ru - not blocked
webview.unityads.unity3d.com - not blocked
adfstat.yandex.ru - not blocked
metrika.yandex.ru - not blocked
auction.unityads.unity3d.com - not blocked
iot-eu-logser.realme.com - not blocked
data.mistat.xiaomi.com - not blocked
iot-logser.realme.com - not blocked
config.unityads.unity3d.com - not blocked
api.ad.xiaomi.com - not blocked
tracking.rus.miui.com - not blocked
data.mistat.india.xiaomi.com - not blocked
bdapi-ads.realmemobile.com - not blocked
adserver.unityads.unity3d.com - not blocked
bdapi-in-ads.realmemobile.com - not blocked
metrics2.data.hicloud.com - not blocked
ck.ads.oppomobile.com - not blocked
sdkconfig.ad.intl.xiaomi.com - not blocked
data.mistat.rus.xiaomi.com - not blocked
data.ads.oppomobile.com - not blocked
sdkconfig.ad.xiaomi.com - not blocked
adx.ads.oppomobile.com - not blocked
open.oneplus.net - not blocked
grs.hicloud.com - not blocked
logservice.hicloud.com - not blocked
logbak.hicloud.com - not blocked
adsfs.oppomobile.com - not blocked
metrics.data.hicloud.com - not blocked
click.oneplus.cn - not blocked
samsungads.com - not blocked
smetrics.samsung.com - not blocked
logservice1.hicloud.com - not blocked
nmetrics.samsung.com - not blocked
analytics-api.samsunghealthcn.com - not blocked
samsung-com.112.2o7.net - not blocked
iadsdk.apple.com - not blocked
metrics.icloud.com - not blocked
advertising.apple.com - not blocked
metrics.mzstatic.com - not blocked
notes-analytics-events.apple.com - not blocked
weather-analytics-events.apple.com - not blocked
api-adservices.apple.com - not blocked
books-analytics-events.apple.com - not blocked
-----
Total : 140
Blocked : 1
Not Blocked : 139]

**Dev Console:**
[N/A]

### Confirmation
- [x] I confirm that I have filled out all the necessary fields with enough detail to allow for the proper investigation and potential resolution of the issue.

**Comment by d3ward** [comment]
Hi, first of all thank you for actually taking the time to fill in the necessary fields, it's something not everyone does. 
Do you have the blocking page feature of NextDNS enabled? that could be why you are doing 1%, check if this feature is enabled and if so, test again by temporarily disabling it, then of course enable back if it's a feature you use.
For NextDNS compatibility table we have this : 
<img width="639" alt="image" src="https://github.com/d3ward/toolz/assets/39910418/50670c0a-53dc-4c77-8e5c-a689c5b69302">

**Comment by Alex67693** [comment]
Hello,

the blocking page was disabled all the time. I now run the test again and
it suddenly shows 97%. So it's working now.

Eduard Ursu ***@***.***> schrieb am Di., 5. März 2024, 22:43:
