### ISSUE TITLE
Test Passed 100%

### ISSUE THREAD

**Issue by relvinarsenio** [d3ward/toolz#124]
**Browser: Microsoft Edge**
**OS: Windows 11**
**Adblock Solution: AdGuard AdBlock Extension**

**Test Passed Value ( 100% ):**

**Description:**
I Use [this](https://github.com/d3ward/toolz/files/14739035/20240325_120204_adg_ext_settings_4.3.31.json) configuration without d3Host List
With [this](https://github.com/d3ward/toolz/files/14739035/20240325_120204_adg_ext_settings_4.3.31.json) configuration, all ads on almost all websites are blocked without damaging the original website.

**Screenshots:**
![image](https://github.com/d3ward/toolz/assets/88470966/981eb378-afb8-45fb-927b-b166ab4c5d3c)

**Test Result Data:**
![image](https://github.com/d3ward/toolz/assets/88470966/3ad68128-3758-4d23-b52c-a1c75b0cfdba)

**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs  from the developer console]

**Comment by d3ward** [comment]
Thanks ! Added in the compatibility table
