### ISSUE TITLE
https://adtools.facebook.com/ is NXDOMAIN

### ISSUE THREAD

**Issue by chirag127** [d3ward/toolz#13]
**Issue URL** : https://adtools.facebook.com/

> because  https://adtools.facebook.com/ is NXDOMAIN it gives DNS_PROBE_FINISHED_NXDOMAIN error and give 2 % blocking even if i'm not using any blocking.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126034182-b61d7b36-fb32-4b5b-ba9f-cea8604aacaf.png)

</details><br/>

**Comment by d3ward** [comment]
This host has been removed to avoid false positive . Seems that this domain is not online even if related to facebook , thanks !
