### ISSUE TITLE
Cannot block

### ISSUE THREAD

**Issue by gn8bln** [d3ward/toolz#136]
### Context

**Safari iOS**:

**iOS**:

**Adblock Solution**:

**Description of Issue**:
advertising-api-eu.amazon.com Canon block this

**Screenshots:**

Already done but no response Ryan asking how I did them

### Logs
N/A
**Test Result:**
N/A

**Test Log:**
N/A

**Dev Console:**
N/A

### Confirmation
- [X] I confirm that I have filled out all the necessary fields with enough detail to allow for the proper investigation and potential resolution of the issue.

**Comment by gn8bln** [comment]
Am 1. Mai 2024, 16:40 +0200 schrieb github-actions[bot] ***@***.***>:
	Hello @gn8bln, it looks like your issue is missing some required information:

• Browser: Safari (as I told)
• OS: iOS (as I told)
• Adblock Solution toolz
• Description of Issue: advertising-api-eu.amazon.com cannot be blocked
luckyorange.com cannot be blocked

• Test Result: N/A
Please update your issue to include this information.

**Comment by d3ward** [comment]
This particular host has been removed as part of the clean-up of specific advertising dashboards, as most of them do not serve ads and are redirects.
