### ISSUE TITLE
Remove Cryptojacking by Opera 

### ISSUE THREAD

**Issue by chirag127** [d3ward/toolz#15]
https://cryptojackingtest.com/ redirects to https://www.opera.com/

Crypto jacking by Opera is obsolete

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/126068093-9b528f95-34d6-426f-9d32-26d36bf8137e.png)

![image](https://user-images.githubusercontent.com/76880977/126068121-33067171-6e03-42d7-8d3e-bb273081c459.png)

</details><br/>

**Comment by d3ward** [comment]
Thanks . Updated and removed the link
