### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by samusa099** [d3ward/toolz#151]
The test relies on JavaScript, it can encounter problems due to browser limitations and varying solution approaches.
Below you'll find browser-adblock solutions that have been validated and tested to work effectively

You will not see any ads and no trackers will be activated
A configuration with multiple solutions at the same time can lead to false positives.
While some browser+adblock solutions may not be supported by this test it's important to note that this does not imply they are not effective or reliable

**Comment by samusa099** [comment]
![ScreenShot_20240813223627](https://github.com/user-attachments/assets/af714e95-9698-42b2-990a-8a801a9bdd8f)

**Comment by d3ward** [comment]
Can you explain what this is about? I see you have just reposted what is on the test info.
