### ISSUE TITLE
PiHole does not block adlist

### ISSUE THREAD

**Issue by EnderRobber101** [d3ward/toolz#156]
### Context

**Browser**:
Safari (content blocker off)
**Operating System**:
Macos
**Adblock Solution**:
Pihole
**Description of Issue**:

I was added ```https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock``` adlist in pihole but it still only had a 46% block rate when testing on the adblock tester.
**Screenshots:**

[Attach screenshots here if applicable]

### Logs

**Test Result:**
[Describe the result of the test]
The result of the blocking was only 46% with pihole with the ad list in this github repository while ublock origin and adgaurd has 100% block rate.
**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs or error messages from the developer console]
No Errors
### Confirmation
- [V ] I confirm that I have filled out all the necessary fields with enough detail to allow for the proper investigation and potential resolution of the issue.

**Comment by wnstfy** [comment]
I have the same issue. Connected to my wireguard, but Zen looks like ignore it somehow.. Firefox and other browsers are okay and pihole blocks it.

**Comment by EnderRobber101** [comment]
I forgot to change my browser dns
