### ISSUE TITLE
xp.apple.com - needed for macOS, iOS, and tvOS software updates

### ISSUE THREAD

**Issue by Zelo72** [d3ward/toolz#16]
xp.apple.com - Network access to this hostname is required for installing, restoring, and updating macOS, iOS, and tvOS:
https://support.apple.com/en-us/HT210060

**Comment by d3ward** [comment]
Thank you for the report

**Comment by Quorum75** [comment]
Hum... This domain is blocked on my side and no issue at all to update all my Apple devices.

**Comment by TFWol** [comment]
@Quorum75 same here. Although I never get a notification that there is an update to be had.
It's the reason why I'm going through these urls again since I've blocked so many :D
