### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by daNutzzzzz** [d3ward/toolz#17]
Possible to create a tool for creating and testing specific network IP/protocol access from the clients machine?

**Comment by d3ward** [comment]
That was a nice idea but too complex for a simple webapp. I will consider to make a simple ip/network detection in future

**Comment by daNutzzzzz** [comment]
Shame, however thank you for you for responding. I look forward to seeing your future project, could you ping me when it is published? :) thanks
