### ISSUE TITLE
google-adservices.com isn't a google domain.

### ISSUE THREAD

**Issue by ryanbr** [d3ward/toolz#21]
"google-adservices.com" Isn't a google domain, is a spam domain. 

In a more general opinion, Are these recently added domain's are they checked beforehand and in use by third-party sites?

**Comment by d3ward** [comment]
I wrongly assumed is from google , most of time i check the domain if it's blocked in big lists like https://oisd.nl/ , and i don't think too much to check each domain . But i see the problem it can cause so for all the new domains i will add and for current ones i will do a full test with whois, lookup and other tools to make sure the list it's solid . Thank you ! ( issue will be closed at next update )

**Comment by d3ward** [comment]
Fixed by @Zelo72 on #22 ! Thank you !
