### ISSUE TITLE
Zelo72

### ISSUE THREAD

**Issue by RicoHeat** [d3ward/toolz#27]
@d3ward Unfortunately https://github.com/Zelo72/ is no longer available.. 
Too bad because his converted version of your list to a adblock Syntax came in handy.

**Comment by d3ward** [comment]
Hi , thanks for letting me know about that ! Sad that Zelo72 closed his account and all the related repos , i was a fan of his lists too . 
I have uploaded the latest .adblock file and will update it from time to time in the future. 

Here you go [d3Host List](https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock)
