### ISSUE TITLE
Improve Ad Block test - make it randomized

### ISSUE THREAD

**Issue by badmojr** [d3ward/toolz#28]
see https://api.webprobe.org/scan/ for inspiration.

**Comment by d3ward** [comment]
Hello , i'm still working on v2 of the test tool with improved UI and more functionalities , soon i should deploy it . 
I have a question , what you mean by "randomized" ??

**Comment by badmojr** [comment]
Whenever one runs the test on the link above, different/random domains get called.
Give it a trial run & log the domains it uses for testing...

**Comment by d3ward** [comment]
Ok so , did some testing and checks . The way the website test is quite different from mine where i check host-by-host with a get/head request . I'm closing the issue as i'm already working on v2.0 of Toolz with some new features
