### ISSUE TITLE
Make adblock test contains css blocker

### ISSUE THREAD

**Issue by billdu1007** [d3ward/toolz#29]
have a <div> that's class is like "adsbygoogle" and use document.getElementByClassName("adsbygoogle").width==0;
if it's true, that means it can block google ads correctly, use other class name like"ad" or "ad" and so on.

**Comment by d3ward** [comment]
Love that idea ! I will try to put that in the version 2.0 of Toolz

**Comment by billdu1007** [comment]
thanks
