### ISSUE TITLE
PiHole +  https://analytics.pointdrive.linkedin.com

### ISSUE THREAD

**Issue by agodlydeciple** [d3ward/toolz#3]
Honestly, not sure if this a bug or not. 

I have blacklisted https://analytics.pointdrive.linkedin.com in pihole, along with several other URLs.

However, every time I rerun, that url is still showing as not blocked. 

![image](https://user-images.githubusercontent.com/683837/115966611-0f43a900-a4f4-11eb-8d9b-c4a81b1b0d8e.png)

Any thoughts as to what I may be missing?

**Comment by d3ward** [comment]
On what browser do you face this issue ? 
As i already pointed out , with some browser the error of blocked connection is different as is not a standard , so the tool may be not able to always detect the blocked host

**Comment by agodlydeciple** [comment]
It was on Firefox, I am not sure of the version.  I must of missed your comment about it! 

Thanks again for the great product!
