### ISSUE TITLE
Provide more detailed definition of testing paramters to users

### ISSUE THREAD

**Issue by based-ghost** [d3ward/toolz#32]
First off, thanks for making this web app as its a great way to spotcheck blocking rules.

This is not really an issue, but I believe adding a message somewhere reminding users that blocking rules may also be defined at the DNS level or in a hosts file (non-mobile devices). This could be important to non-technical users or those that may want to test their browser and/or DNS in isolation.

**Example:** I ran a test on GrapheneOS's stock browser - Vandium - and it initially reported a 77% (which struck me as odd since it focuses on security over privacy). However, the issue was that the blocking rules were coming from my VPN's DNS and after switching that off the reported score was 10%.  If I were to change my DNS in the future, I could be left exposed - provided with a false sense of security in regards to my browser's adblocking capabilities.

**Comment by d3ward** [comment]
Thanks for that feedback , on new major update Ii will include a dedicated section that explain and showcase how different scenarios affect the test
