### ISSUE TITLE
Request of Cleverads.vn [https://cleverads.vn/] Domain Removal from Blocklist

### ISSUE THREAD

**Issue by Buithanhhuong** [d3ward/toolz#33]
Hello,

We would like to make a complaint about this status and request to remove [cleverads.vn](http://cleverads.vn/) from the blocklist.

Cleverads.vn is a website that provides information of Digital Marketing services, it is neither an ad network, nor an ad platform displayed on a third-party website, so we think that putting [cleverads.vn](http://cleverads.vn/) on blocklist is incorrect and inappropriate, which is making a direct negative impact on our business.

We respectfully and strongly request to respond to this issue for the Parties to work on this matter promptly, and to immediately remove [cleverads.vn](http://cleverads.vn/) from your blocklist.

You can contact me by email [huong.bui@clevergroup.vn](mailto:huong.bui@clevergroup.vn) or by phone number (+84)988079654
Thank you very much!

**Comment by d3ward** [comment]
1.  The domain "[cleverads.vn](http://cleverads.vn/)" is not even in my blocklist , but a subdomain reported by thousands of users 
2.  I wonder why your domain it's on 99% of blocklists....... maybe I should add that too !
3. This is a open source project and users have free will to use or not my personal blocklist 
4. I will never remove suspicious domains from the blocklist
