### ISSUE TITLE
remove data.mistat.intl.xiaomi from d3host / AdBlock-Test

### ISSUE THREAD

**Issue by hagezi** [d3ward/toolz#34]
Blocking data.mistat.intl.xiaomi blocks update checking, see:

https://www.reddit.com/r/oisd_blocklist/comments/m6j6fg/comment/gxe4f7d/?context=3
https://github.com/badmojr/1Hosts/issues/392

**Comment by d3ward** [comment]
Thanks for that

**Comment by d3ward** [comment]
Removed domain from v3.0.0
