### ISSUE TITLE
Invalid tests

### ISSUE THREAD

**Issue by Alex-302** [d3ward/toolz#38]
`adsdk.yandex.ru` - not used to load scripts or banners, just clickthrough.
`googleadservices.com` and `@@://googleadservices.com^|` - exclusion does not unblock any scripts or ads, also used as clickthrough in google search ads(to prevent links breakage, when user does not use element hiding)
`analytics.facebook.com` not used for analytics, it is FB's old blog address

**Comment by d3ward** [comment]
Removed this domains in v3.0.0
