### ISSUE TITLE
Add more domains to adblocking test

### ISSUE THREAD

**Issue by GiddyGoatGaming** [d3ward/toolz#42]
I think there should be a few more domains added to d3ward Adblock testing. These include domains

app-measurement.com (under google analytics)

And a whole section with these domains

ads.aerserv.com
ads.avocarrot.com
ads30.adcolony.com
adc3-launch.adcolony.com
events3alt.adcolony.com
wd.adcolony.com
events3alt.adcolony.com
adserver.unityads.unity3d.com
d.applvn.com
app.appsflyer.com
config.unityads.unity3d.com
a.applvn.com
admin.appnext.com
auction.unityads.unity3d.com
rt.applovin.com
live.chartboost.com
v2.chartboost.com
rt.applvn.com
webview.unityads.unity3d.com

All of which are used to serve ads to people. These domains were taken from https://github.com/AdAway/AdAway/issues/922

Let me know what you think of this request.

**Comment by d3ward** [comment]
Although I wish I could add these domains, they are not well categorised and do not fit into the test tool

**Comment by GiddyGoatGaming** [comment]
What if you took the unity ads and adcolony domains and created 2 new categories out of them?

**Comment by d3ward** [comment]
not a bad idea actually . adcolony under Ads and unity under Mix . Done

**Comment by GiddyGoatGaming** [comment]
> not a bad idea actually . adcolony under Ads and unity under Mix . Done

Sounds good, thanks!

**Comment by d3ward** [comment]
Thank you !
