### ISSUE TITLE
list is not 100%

### ISSUE THREAD

**Issue by Vansmak** [d3ward/toolz#43]
I always get 87% even after adding your d3 list and clearig cache.  It is always doubleclick, fastclick and social media trackers that fail.  your site says the list you crested blocks 100% of tests but it doesnt.

**Comment by d3ward** [comment]
Yes I'm aware of this inconsistency. I got hundred of reports so the next version in fact will include improved detection of different adblock solutions

**Comment by d3ward** [comment]
Upcoming version have improved detection , and more details on compatibility with different solutions
