### ISSUE TITLE
Domains to add to current categories

### ISSUE THREAD

**Issue by SpencerIsGiddy** [d3ward/toolz#47]
Currently  

TikTok list is missing:
log.tiktokv.com
log.byteoversea.com

Apple is missing:
api-adservices.apple.com
books-analytics-events.apple.com
iadsdk.apple.com
ca.iadsdk.apple.com
cf.iadsdk.apple.com
metrics.apple.com
notes-analytics-events.apple.com
securemvt.apple.com
weather-analytics-events.apple.com
books-analytics-events.news.apple-dns.net
notes-analytics-events.news.apple-dns.net
weather-analytics-events.news.apple-dns.net
acfeedbackws.icloud.com
feedbackws.icloud.com
dzc-metrics.mzstatic.com
metrics.mzstatic.com

Samsung is missing:
nmetrics.samsung.com
analytics.samsungknox.com

take as you wish!

**Comment by d3ward** [comment]
TikTok:
log.tiktokv.com - 404
log.byteoversea.com - **added**
Apple: 
api-adservices.apple.com - **added**
books-analytics-events.apple.com - **added**
iadsdk.apple.com - **added**
ca.iadsdk.apple.com - subdomain of iadsdk.apple.com
cf.iadsdk.apple.com - subdomain of iadsdk.apple.com
metrics.apple.com - **added**
notes-analytics-events.apple.com - **added**
securemvt.apple.com - 404
weather-analytics-events.apple.com - **added**
books-analytics-events.news.apple-dns.net - 404
notes-analytics-events.news.apple-dns.net - 404
weather-analytics-events.news.apple-dns.net - 404
acfeedbackws.icloud.com - 400
feedbackws.icloud.com - 400
dzc-metrics.mzstatic.com - timeout
metrics.mzstatic.com - **added**
Samsung: 
nmetrics.samsung.com - **added**
analytics.samsungknox.com - timeout

Doesn't make sense to add too many that do not resolve or are on 400 range + didn't want to make the list too long  so I picked some from the list . Thanks !
