### ISSUE TITLE
fritzbox 7590 + freshmarketer.com

### ISSUE THREAD

**Issue by KastenKlicker** [d3ward/toolz#5]
I blacklisted freshmarketer.com at the Blacklist of my router fritzbox 7590. But when I run the test in firefox it says it's not blocked. 
I can't access the URL through firefox, showing it's blocked.
Chrome/Brave are displaying that it's blocked.

**Comment by squadramunter** [comment]
This tool is for Pi-Hole only and not for Fritz!Box

**Comment by KastenKlicker** [comment]
It doesn't matter if the fritzblock blocks the domain or the Pi Hole. Both got a Blacklist for Domains.

But thank you for your reply, I ran the test again and now it shows it's blocked.
