### ISSUE TITLE
analytics.twitter.com |  CNAME ads.twitter.com

### ISSUE THREAD

**Issue by hagezi** [d3ward/toolz#54]
Hi,

`analytics.twitter.com` -  CNAME `ads.twitter.com`

These are not classic analytics domains, they are referral domains through which links are called from tweets.

Cheers,
Gerd

**Comment by d3ward** [comment]
I actually had doubts for days about it . A lot of smaller lists blocks it and didn't hear so much about issues. But I see they looks like simple analytic dashboard and the reason are whitelisted . Updated the list and removed these 2 for consistency. 
Thank you for the feedback !
