### ISSUE TITLE
Blocking all JavaScript is bad?

### ISSUE THREAD

**Issue by GreenMan36** [d3ward/toolz#56]
If you block all JS by default, the test will look like this:
![image](https://user-images.githubusercontent.com/5887406/226443555-a4521044-c835-449a-be3b-83dec29593aa.png)
Which is fine I guess...?

Ideally you'd have the plain HTML show you something like,
> Great! You seem to be blocking all JavaScript!... 
> but the test can't check if other requests are blocked without Javascript so you should allow JavaScript and run the test again."

And then remove or adjust the message after enabling JS.
Having JS blocked by default is a great privacy and adblocking tool.

**Comment by krystian3w** [comment]
You can use `<noscript>` to avoid remove/hide in JS.

**Comment by GreenMan36** [comment]
```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			#double-check {background:darkgreen};
			span + #double-check {display:none};
			span, noscript, noscript + #double-check {background:darkred};
		</style>
	</head>
	<body style="color: white; background: black;">
		<noscript>
			JavaScript needs to be enabled for this page to work.
		</noscript>
		<div id="double-check">
			Cool, so... the browser says that JS is enabled but... this div should've changed content... so its not really.
		<div>
		<script>
		const div = document.querySelector("#double-check");
		div.innerText = "Seems like JS is working!";
		</script>
	</body>
</html>
```

Here's a little test file that can be used.
My result:
![image](https://user-images.githubusercontent.com/5887406/229346007-dfd69776-bbec-4f98-9742-a7fe9adb6d99.png)
Settings: 
![image](https://user-images.githubusercontent.com/5887406/229346023-1b08d2e5-bea6-49fa-a39e-d76ec48ee10c.png)


@krystian3w  As you can see, the browser's built-in check isn't really that good... I allow _some_ JS but block most 3rd party and imports. That's what seems to trip stuff up. Although I haven't made a check for importing third-party scripts. 
So its not really the add-on badly deactivating JS support, it only blocks what you've told it to and the browser's detection is just poor.

**Comment by krystian3w** [comment]
Or webpage have bugs:

* Disabled by `about:config`:
   
   ![obraz](https://user-images.githubusercontent.com/35370833/229350016-c0abd39b-afe4-4a6d-b711-c65dd2003b2b.png)

* Disabled by WebExtension:

  ![obraz](https://user-images.githubusercontent.com/35370833/229350145-42b1bc03-b4d9-40c9-b34f-7558f7803fbe.png)

**Comment by d3ward** [comment]
The main issue we have there is that a test like that actually need JS in order to works properly . In this case the "BAD"  is unintentional because we have red-orange-green . So the "bad has nothing to do with the fact that you disabled JS completely. Anyway the topic about disabling or not JS is very complex and have too many points to discuss. 
If you have JS disabled , I don't think you should d any kind of test overall .
@GreenMan36 @krystian3w thanks for your input on a possible solution, I'll try to improve that UX on the test .

**Comment by krystian3w** [comment]
My point was that you can't fire up the test directly from HDD/SSD like that without running a local HTTP server.

**Comment by krystian3w** [comment]
As for detecting the substitution of a file for a surrogate then maybe you need to check Google's free file personalization (GA4, gtm, etc) and see if the personalized code executes.

**Comment by d3ward** [comment]
Recent update added support for no JS situation . This works for  project/files run from server.
