### ISSUE TITLE
Problem with cache in browser

### ISSUE THREAD

**Issue by squadramunter** [d3ward/toolz#6]
When I started the test it gives me points on what I could improve  the second test did not changed anything because it seems to cache in the browser. With incognito it did work.

I like to see if the cache is deleted when the page loads again

**Comment by squadramunter** [comment]
I am running this on latest Google Chrome

**Comment by d3ward** [comment]
Do you still have that bug ? Im taking a look these days and can't reproduce the bug

**Comment by d3ward** [comment]
Closing as this is related to the used browser
