### ISSUE TITLE
d3ward hosts

### ISSUE THREAD

**Issue by diegodambra** [d3ward/toolz#61]
The `src/d3hosts.txt` list the below Mouseflow endpoints that are irrelevant for analytics, tracking or delivery of Mouseflow services.

```
0.0.0.0 api.mouseflow.com
0.0.0.0 tools.mouseflow.com
0.0.0.0 cdn-test.mouseflow.com
```
When users does an adblock test, the 3 above hosts are visited? Result means nothing in regard to analytics.

Kindly consider removing them, thanks.

**Comment by d3ward** [comment]
Sorry, no plans to remove these.
Mouseflow is a tracking solution and all subdomains must be blocked even though they are not used for analytics/tracking purposes, we don't have any docs on what they are used for, plus most popular big lists actually block them.

**Comment by hagezi** [comment]
Yes, it's tracking and a lot of fingerprinting APIs are used:

https://slayterdev.github.io/tracker-radar-wiki/domains/mouseflow.com.html
https://whotracks.me/trackers/mouseflow.html
