### ISSUE TITLE
500 Handling error codes

### ISSUE THREAD

**Issue by nicekon** [d3ward/toolz#62]
Some ad blockers return a 500 error code for blocking requests (e.g., adguard).

**Comment by d3ward** [comment]
I'll address this issue on next update . Thanks

**Comment by d3ward** [comment]
Unfortunately 500 error code cannot be intercepted with JS. 
I added Adguard ( app ) to the table compatibility with info.
PS. Adguard app solution works perfectly , using the simple but official test https://adguard.com/en/test.html can help at least know if the blocking runs.
