### ISSUE TITLE
Adguard 100% Test

### ISSUE THREAD

**Issue by RelvinArsenio** [d3ward/toolz#69]
**Browser: Microsoft Edge**
**OS: Windows 11**
**Adblock Solution: AdGuard AdBlocker (Browser Extension)**

**Test Passed Value ( 100% ):**

**Description:**
Adguard Filter List
- [x] AdGuard Base filter
- [x] AdGuard Mobile Ads filter
- [x] AdGuard URL Tracking filter
- [x] AdGuard Tracking Protection filter
- [x] Legitimate URL Shortener
- [x] AdGuard Annoyances filter
- [x] AdGuard Cookie Notices filter
- [x] AdGuard Popups filter
- [x] AdGuard Mobile App Banners filter
- [x] AdGuard Other Annoyances filter
- [x] AdGuard Widgets filter
- [x] Adblock Warning Removal List
- [x] ABPindo
- [x] AdBlockID

 **Custom Filter List**
- [x] [HaGeZi's Light DNS Blocklist](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt)

**Screenshots:**
![image](https://github.com/d3ward/toolz/assets/88470966/61a35009-fc17-4d15-8e18-5826258d0797)
![image](https://github.com/d3ward/toolz/assets/88470966/887dc832-788a-4c0e-a757-e9af7571217b)
![image](https://github.com/d3ward/toolz/assets/88470966/011e9211-72dd-4827-859a-4aa9150ac1c9)
![image](https://github.com/d3ward/toolz/assets/88470966/cd76f7b4-0e63-46e2-8b45-e407cd402dcb)

**Test Result Data:**
![image](https://github.com/d3ward/toolz/assets/88470966/a54e98e2-0520-4649-aaaf-eb7d92f52e03)

**Test Log:**

script_ads : true
script_pagead : true
script_partenrads : true

-------------------------
Amazon => n° tests => 5
Google Ads => n° tests => 4
Doubleclick.net => n° tests => 5
Adcolony => n° tests => 4
Media.net => n° tests => 3
Ads => Total n° tests => 21
-------------------------
Google Analytics => n° tests => 5
Hotjar => n° tests => 7
MouseFlow => n° tests => 7
FreshWorks => n° tests => 3
Luckyorange => n° tests => 8
Stats WP Plugin => n° tests => 1
Analytics => Total n° tests => 31
-------------------------
Bugsnag => n° tests => 4
Sentry => n° tests => 2
Error Trackers => Total n° tests => 6
-------------------------
Facebook => n° tests => 2
Twitter => n° tests => 2
LinkedIn => n° tests => 2
Pinterest => n° tests => 5
Reddit => n° tests => 2
YouTube => n° tests => 1
TikTok => n° tests => 7
Social Trackers => Total n° tests => 21
-------------------------
Yahoo => n° tests => 11
Yandex => n° tests => 7
Unity => n° tests => 4
Mix => Total n° tests => 22
-------------------------
Realme => n° tests => 4
Xiaomi => n° tests => 8
Oppo => n° tests => 4
Huawei => n° tests => 6
OnePlus => n° tests => 2
Samsung => n° tests => 5
Apple => n° tests => 10
OEMs => Total n° tests => 39
-------------------------
cosmetic_static_ad : true

-------------------------
cosmetic_dynamic_ad : true

-------------------------

adtago.s3.amazonaws.com - blocked
analyticsengine.s3.amazonaws.com - blocked
analytics.s3.amazonaws.com - blocked
advice-ads.s3.amazonaws.com - blocked
advertising-api-eu.amazon.com - blocked
pagead2.googlesyndication.com - blocked
adservice.google.com - blocked
pagead2.googleadservices.com - blocked
afs.googlesyndication.com - blocked
stats.g.doubleclick.net - blocked
ad.doubleclick.net - blocked
static.doubleclick.net - blocked
m.doubleclick.net - blocked
mediavisor.doubleclick.net - blocked
ads30.adcolony.com - blocked
adc3-launch.adcolony.com - blocked
events3alt.adcolony.com - blocked
wd.adcolony.com - blocked
static.media.net - blocked
media.net - blocked
adservetx.media.net - blocked
app-measurement.com - blocked
analytics.google.com - blocked
click.googleanalytics.com - blocked
google-analytics.com - blocked
ssl.google-analytics.com - blocked
adm.hotjar.com - blocked
identify.hotjar.com - blocked
insights.hotjar.com - blocked
script.hotjar.com - blocked
surveys.hotjar.com - blocked
careers.hotjar.com - blocked
events.hotjar.io - blocked
mouseflow.com - blocked
cdn.mouseflow.com - blocked
o2.mouseflow.com - blocked
gtm.mouseflow.com - blocked
api.mouseflow.com - blocked
tools.mouseflow.com - blocked
cdn-test.mouseflow.com - blocked
freshmarketer.com - blocked
claritybt.freshmarketer.com - blocked
fwtracks.freshmarketer.com - blocked
luckyorange.com - blocked
api.luckyorange.com - blocked
realtime.luckyorange.com - blocked
cdn.luckyorange.com - blocked
w1.luckyorange.com - blocked
upload.luckyorange.net - blocked
cs.luckyorange.net - blocked
settings.luckyorange.net - blocked
stats.wp.com - blocked
notify.bugsnag.com - blocked
sessions.bugsnag.com - blocked
api.bugsnag.com - blocked
app.bugsnag.com - blocked
browser.sentry-cdn.com - blocked
app.getsentry.com - blocked
pixel.facebook.com - blocked
an.facebook.com - blocked
static.ads-twitter.com - blocked
ads-api.twitter.com - blocked
ads.linkedin.com - blocked
analytics.pointdrive.linkedin.com - blocked
ads.pinterest.com - blocked
log.pinterest.com - blocked
analytics.pinterest.com - blocked
trk.pinterest.com - blocked
widgets.pinterest.com - blocked
events.reddit.com - blocked
events.redditmedia.com - blocked
ads.youtube.com - blocked
ads-api.tiktok.com - blocked
analytics.tiktok.com - blocked
ads-sg.tiktok.com - blocked
analytics-sg.tiktok.com - blocked
business-api.tiktok.com - blocked
ads.tiktok.com - blocked
log.byteoversea.com - blocked
ads.yahoo.com - blocked
analytics.yahoo.com - blocked
geo.yahoo.com - blocked
udc.yahoo.com - blocked
udcm.yahoo.com - blocked
advertising.yahoo.com - blocked
analytics.query.yahoo.com - blocked
partnerads.ysm.yahoo.com - blocked
log.fc.yahoo.com - blocked
gemini.yahoo.com - blocked
adtech.yahooinc.com - blocked
extmaps-api.yandex.net - blocked
appmetrica.yandex.ru - blocked
adfstat.yandex.ru - blocked
metrika.yandex.ru - blocked
advertising.yandex.ru - blocked
offerwall.yandex.net - blocked
adfox.yandex.ru - blocked
auction.unityads.unity3d.com - blocked
webview.unityads.unity3d.com - blocked
config.unityads.unity3d.com - blocked
adserver.unityads.unity3d.com - blocked
iot-eu-logser.realme.com - blocked
iot-logser.realme.com - blocked
bdapi-ads.realmemobile.com - blocked
bdapi-in-ads.realmemobile.com - blocked
api.ad.xiaomi.com - blocked
data.mistat.xiaomi.com - blocked
data.mistat.india.xiaomi.com - blocked
data.mistat.rus.xiaomi.com - blocked
sdkconfig.ad.xiaomi.com - blocked
sdkconfig.ad.intl.xiaomi.com - blocked
globalapi.ad.xiaomi.com - blocked
tracking.rus.miui.com - blocked
adsfs.oppomobile.com - blocked
adx.ads.oppomobile.com - blocked
ck.ads.oppomobile.com - blocked
data.ads.oppomobile.com - blocked
metrics.data.hicloud.com - blocked
metrics2.data.hicloud.com - blocked
grs.hicloud.com - blocked
logservice.hicloud.com - blocked
logservice1.hicloud.com - blocked
logbak.hicloud.com - blocked
click.oneplus.cn - blocked
open.oneplus.net - blocked
samsungads.com - blocked
smetrics.samsung.com - blocked
nmetrics.samsung.com - blocked
samsung-com.112.2o7.net - blocked
analytics-api.samsunghealthcn.com - blocked
advertising.apple.com - blocked
tr.iadsdk.apple.com - blocked
iadsdk.apple.com - blocked
metrics.icloud.com - blocked
metrics.apple.com - blocked
metrics.mzstatic.com - blocked
api-adservices.apple.com - blocked
books-analytics-events.apple.com - blocked
weather-analytics-events.apple.com - blocked
notes-analytics-events.apple.com - blocked
-----
Total : 150
Blocked : 150
Not Blocked : 0

**Comment by marcelloinfoweb** [comment]
I tested it and it didn't work 100%.

![image](https://github.com/d3ward/toolz/assets/2093128/aa544797-4e24-4cd7-9d9a-2b9761b1ecf9)

**Comment by RelvinArsenio** [comment]
> * HaGeZi's Light DNS Blocklist

Add this custom filter list

- [HaGeZi's Light DNS Blocklist](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt)

**Comment by RelvinArsenio** [comment]
> I tested it and it didn't work 100%.
> 
> ![image](https://user-images.githubusercontent.com/2093128/258811628-aa544797-4e24-4cd7-9d9a-2b9761b1ecf9.png)

Add this custom filter list:
- [HaGeZi's Light DNS Blocklist](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt)

**Comment by marcelloinfoweb** [comment]
These continue without blocking, which lists more you do?

![image](https://github.com/d3ward/toolz/assets/2093128/94bd5eb6-4a92-41c5-81a8-d3572007be6f)

**Comment by marcelloinfoweb** [comment]
> > I tested it and it didn't work 100%.
> > ![image](https://user-images.githubusercontent.com/2093128/258811628-aa544797-4e24-4cd7-9d9a-2b9761b1ecf9.png)
> 
> Add this custom filter list:
> 
> * [HaGeZi's Light DNS Blocklist](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt)

I already use this list

**Comment by marcelloinfoweb** [comment]
> These continue without blocking, which lists more you do?
> 
> ![image](https://user-images.githubusercontent.com/2093128/259406529-94bd5eb6-4a92-41c5-81a8-d3572007be6f.png)

What about it?

**Comment by RelvinArsenio** [comment]
Filters that are not listed above must be deactivated

> > These continue without blocking, which lists more you do?
> > ![image](https://user-images.githubusercontent.com/2093128/259406529-94bd5eb6-4a92-41c5-81a8-d3572007be6f.png)
> 
> What about it?

Note: Based on the test that I did, filters that are not listed above should be deactivated if you want 100%.

```json
{
    "protocol-version": "2.0",
    "general-settings": {
        "allow-acceptable-ads": false,
        "show-blocked-ads-count": true,
        "autodetect-filters": false,
        "safebrowsing-enabled": true,
        "filters-update-period": -1,
        "appearance-theme": "system"
    },
    "extension-specific-settings": {
        "use-optimized-filters": false,
        "collect-hits-count": false,
        "show-context-menu": true,
        "show-info-about-adguard": false,
        "show-app-updated-info": true,
        "hide-rate-adguard": false,
        "user-rules-editor-wrap": false
    },
    "filters": {
        "enabled-filters": [
            2,
            3,
            11,
            14,
            17,
            18,
            19,
            20,
            21,
            22,
            102,
            120,
            207,
            251,
            1000,
            1001
        ],
        "enabled-groups": [
            0,
            1,
            2,
            4,
            7
        ],
        "custom-filters": [
            {
                "customUrl": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/gambling.txt",
                "title": "HaGeZi's Gambling DNS Blocklist",
                "trusted": false,
                "enabled": true
            },
            {
                "customUrl": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt",
                "title": "HaGeZi's Light DNS Blocklist",
                "trusted": false,
                "enabled": true
            }
        ],
        "user-filter": {
            "enabled": true,
            "rules": "alpinecorporate.com###a3YvbVh3ZkFmdjNxd0dRTTdna1JUaXEzU2lHUytKNjBCYmF1RWw1dHRwVT0ckppx",
            "disabled-rules": ""
        },
        "allowlist": {
            "enabled": true,
            "inverted": false,
            "domains": [],
            "inverted-domains": []
        }
    },
    "stealth": {
        "stealth-disable-stealth-mode": false,
        "stealth-hide-referrer": true,
        "stealth-hide-search-queries": true,
        "stealth-send-do-not-track": true,
        "stealth-block-webrtc": false,
        "stealth-remove-x-client": false,
        "stealth-block-third-party-cookies": true,
        "stealth-block-third-party-cookies-time": 2880,
        "stealth-block-first-party-cookies": false,
        "stealth-block-first-party-cookies-time": 4320,
        "block-known-trackers": true,
        "strip-tracking-parameters": true
    }
}
```
