### ISSUE TITLE
Iky

### ISSUE THREAD

**Issue by ghost** [d3ward/toolz#71]
**Browser:**
**OS:**
**Adblock Solution:**

**Test Passed Value ( % ):**

**Description:**
[Provide a detailed description of the configuration used ( DNS , VPN, Lists etc.]

**Screenshots:**
[Attach any relevant screenshots or examples if available]

**Test Result Data:**
[Provide exported test result]

**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs  from the developer console]

**Comment by d3ward** [comment]
There is no details about the test
