### ISSUE TITLE
Test Ad block Toolz

### ISSUE THREAD

**Issue by arberkapllani** [d3ward/toolz#72]
**Browser:**
**OS:**
**Adblock Solution:**

**Description of Issue:**

**Screenshots:**
[Attach screenshots here if applicable]

**Test Result:**
[Describe the result of the test]

**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs or error messages from the developer console]

**Comment by d3ward** [comment]
Closing due to missing details
