### ISSUE TITLE
Mullvad VPN Test Results

### ISSUE THREAD

**Issue by ReclinesMC** [d3ward/toolz#77]
**Browser:** Microsoft Edge
**OS:** Windows 11
**Adblock Solution:** Mullvad DNS

**Test Passed Value:** 91%

**Description:**
Using Mullvad VPN with adblock enabled.

**Test Result Data:**
https://paste.gg/p/anonymous/05e0fff032194fc69d078b9b34d265f0

**Test Log:**
https://paste.gg/p/anonymous/608737325be14725b3ea133b816c895f

**Dev Console:**
https://paste.gg/p/anonymous/393150c810a44439b12627ba7e198d55

### Mullvad Settings
![image](https://github.com/d3ward/toolz/assets/48137058/af33421c-38e1-4c94-9615-251376f59884)

**Comment by NiREvil** [comment]
![Screenshot_20240103-231631~01](https://github.com/d3ward/toolz/assets/126243832/0b957da3-ab0d-49a0-b638-3957b46fc84c)

NekoBox + VLESS + Adguard AdBlocker = 97 fuckin percent. Tnx to you dude✋

**Comment by d3ward** [comment]
Thanks ! Added into the compatibility table
