### ISSUE TITLE
Zee5 adds 

### ISSUE THREAD

**Issue by akkavikka8088** [d3ward/toolz#88]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akkavikka8088** [comment]
Zee5 adds not blocked so that's why
Solve this problem

**Comment by d3ward** [comment]
zee5 is not part of the tests, and the test does not aim to fix this automatically. You will need to check with your Adblock solution to include lists that actually block zee5.
