### ISSUE TITLE
The "X not blocked" summary does not match the red box count

### ISSUE THREAD

**Issue by PerMildner** [d3ward/toolz#89]
**Describe the bug**

It is confusing, and possibly a bug, that the summary says "2 not blocked", but there is only one red box.

**To Reproduce**

Visit https://d3ward.github.io/toolz/adblock.html with Mullvad browser (I get the same results with Firefox+various blocker plugins)

The summary says Total 150, 148 blocked, 2 not blocked.

The page shows green for all things, except for Ad Scripts Loading where it has a single red box, for partner.ads.js.

**Expected behavior**

I would expect the number "not blocked" in the summary to match the number of red boxes, _or_ a clearer indication about how many "not blocked" are implied by each red box. I.e., it may be just a documentation problem.

**Screenshots**
<img width="1397" alt="Screenshot 2023-11-15 at 11 15 08" src="https://github.com/d3ward/toolz/assets/1358238/803c6550-5c69-47bd-9efe-544461e7044c">

**Desktop (please complete the following information):**
 - OS: macOS 13.6.1 (22G313) Intel.
 - Browser Mullvad browser. Same result with recent Firefox+blocker-plugins)
 - Version 13.0.1 (based on Mozilla Firefox 115.4.0e.

**Comment by d3ward** [comment]
I agree that it's confusing ... it's happening because the cosmetic filter and ad script loading have 2 points each instead of 1 . I will fix that
