### ISSUE TITLE
Please remove insights.samsung.com from your list

### ISSUE THREAD

**Issue by jeffmann** [d3ward/toolz#9]
Hi, I was unable to access insights.samsung.com, which is Samsung's blog site. It was completely blocked by uBlock with the EasyPrivacy list. I contacted the EasyPrivacy list maintainers, who said that it was added to their block list because of this toolz block/test. They refuse to fix or remove it from EasyPrivacy until it's removed from here. Please check the site, It's not a tracking/ad host, and should not be globally blocked.

I know how to disable the blocking in my browser, but the host doesn't belong in the blocklist in the first place. Could you fix it? Thanks.

**Comment by d3ward** [comment]
Hello , someone did a PR and i accepted it ! 
It was my mistake to include it, thinking it was related to business trackers. It's now fixed

**Comment by jeffmann** [comment]
Thanks!
