### ISSUE TITLE
[Question] What is "partner.ads.js" testing?

### ISSUE THREAD

**Issue by xe-3** [d3ward/toolz#99]
I see that `partner.ads.js` refers to this piece of JS:

> var s_test_partnerads = 'https://youtu.be/dQw4w9WgXcQ'
> console.log('s_test_partnerads : ', s_test_partnerads)`

I don't read javascript, but best I can tell this creates a variable called `s_test_partnerads` which points to a...youtube link. Not sure what the second line does.

I would like to understand what this is actually testing, because I have noticed that this is the only test that is not blocked by the two major content blockers I use (uBlock Origin and Brave).

**Comment by d3ward** [comment]
This script is part of a test to emulate how some websites load ad scripts and tracking scripts. The YouTube link (a classic 'rickroll') is an Easter egg I added for a bit of fun – it's great to see someone noticed it!

No actual ads are loaded by this script. Instead, it's a simulation designed to test if ad-blocking solutions, like uBlock Origin and Brave, effectively block such scripts ( they do !). The inclusion of the script is temporary, and I'm planning to remove it in the future. I appreciate your vigilance and interest in understanding how it works!
